"""Константы протокола EGTS (ГОСТ Р 54619-2011)."""
from datetime import datetime, timezone

# Эпоха EGTS: 2010-01-01 00:00:00 UTC
EPOCH = datetime(2010, 1, 1, tzinfo=timezone.utc)

# Типы пакетов
PT_RESPONSE = 0
PT_APPDATA  = 1

# Типы сервисов
SVC_AUTH     = 1
SVC_TELEDATA = 2

# Длина заголовка по умолчанию (без маршрутизации)
HEADER_LEN_DEFAULT = 11
HEADER_LEN_ROUTED  = 16

# Типы подзаписей SRT
SRT_RECORD_RESPONSE     = 0
SRT_TERM_IDENTITY       = 1
SRT_MODULE_DATA         = 2
SRT_DISPATCHER_IDENTITY = 5
SRT_AUTH_INFO           = 7
SRT_RESULT_CODE         = 9
SRT_EGTS_PLUS_DATA      = 15
SRT_POS_DATA            = 16
SRT_EXT_POS_DATA        = 17
SRT_AD_SENSORS_DATA     = 18
SRT_COUNTERS_DATA       = 19
SRT_STATE_OR_ACCEL      = 20
SRT_STATE_DATA          = 21
SRT_LOOPIN_DATA         = 22
SRT_ABS_DIG_SENS_DATA   = 23
SRT_ABS_AN_SENS_DATA    = 24
SRT_ABS_CNTR_DATA       = 25
SRT_ABS_LOOPIN_DATA     = 26
SRT_LIQUID_LEVEL_SENSOR = 27
SRT_PASSENGERS_COUNTERS = 28
SRT_CUSTOM_200          = 200
SRT_CUSTOM_201          = 201
SRT_CUSTOM_202          = 202
SRT_CUSTOM_203          = 203

SRT_NAMES: dict[int, str] = {
    SRT_RECORD_RESPONSE:     "EGTS_SR_RECORD_RESPONSE",
    SRT_TERM_IDENTITY:       "EGTS_SR_TERM_IDENTITY",
    SRT_MODULE_DATA:         "EGTS_SR_MODULE_DATA",
    SRT_DISPATCHER_IDENTITY: "EGTS_SR_DISPATCHER_IDENTITY",
    SRT_AUTH_INFO:           "EGTS_SR_AUTH_INFO",
    SRT_RESULT_CODE:         "EGTS_SR_RESULT_CODE",
    SRT_EGTS_PLUS_DATA:      "EGTS_SR_EGTS_PLUS_DATA",
    SRT_POS_DATA:            "EGTS_SR_POS_DATA",
    SRT_EXT_POS_DATA:        "EGTS_SR_EXT_POS_DATA",
    SRT_AD_SENSORS_DATA:     "EGTS_SR_AD_SENSORS_DATA",
    SRT_COUNTERS_DATA:       "EGTS_SR_COUNTERS_DATA",
    SRT_STATE_OR_ACCEL:      "EGTS_SR_STATE_DATA|ACCEL",
    SRT_STATE_DATA:          "EGTS_SR_STATE_DATA",
    SRT_LOOPIN_DATA:         "EGTS_SR_LOOPIN_DATA",
    SRT_ABS_DIG_SENS_DATA:   "EGTS_SR_ABS_DIG_SENS_DATA",
    SRT_ABS_AN_SENS_DATA:    "EGTS_SR_ABS_AN_SENS_DATA",
    SRT_ABS_CNTR_DATA:       "EGTS_SR_ABS_CNTR_DATA",
    SRT_ABS_LOOPIN_DATA:     "EGTS_SR_ABS_LOOPIN_DATA",
    SRT_LIQUID_LEVEL_SENSOR: "EGTS_SR_LIQUID_LEVEL_SENSOR",
    SRT_PASSENGERS_COUNTERS: "EGTS_SR_PASSENGERS_COUNTERS",
    SRT_CUSTOM_200:          "EGTS_SR_CUSTOM_SRT200",
    SRT_CUSTOM_201:          "EGTS_SR_CUSTOM_SRT201",
    SRT_CUSTOM_202:          "EGTS_SR_CUSTOM_SRT202",
    SRT_CUSTOM_203:          "EGTS_SR_CUSTOM_SRT203",
}

PT_NAMES: dict[int, str] = {
    PT_RESPONSE: "EGTS_PT_RESPONSE",
    PT_APPDATA:  "EGTS_PT_APPDATA",
}

SVC_NAMES: dict[int, str] = {
    SVC_AUTH:     "EGTS_AUTH_SERVICE",
    SVC_TELEDATA: "EGTS_TELEDATA_SERVICE",
}

RESULT_CODES: dict[int, str] = {
    0:   "EGTS_PC_OK",
    1:   "EGTS_PC_IN_PROGRESS",
    128: "EGTS_PC_UNS_PROTOCOL",
    129: "EGTS_PC_DECRYPT_ERROR",
    130: "EGTS_PC_INC_DATAFORM",
    131: "EGTS_PC_INC_HEADERFORM",
    132: "EGTS_PC_UNS_TYPE",
    133: "EGTS_PC_NOTEN_PARAMS",
    134: "EGTS_PC_DBL_PROC",
    135: "EGTS_PC_PROC_DENIED",
    136: "EGTS_PC_INC_HEADERCRC",
    137: "EGTS_PC_INC_DATACRC",
    138: "EGTS_PC_INVDATALEN",
    139: "EGTS_PC_ROUTE_NFOUND",
    140: "EGTS_PC_ROUTE_CLOSED",
    141: "EGTS_PC_ROUTE_DENIED",
    142: "EGTS_PC_INVADDR",
    143: "EGTS_PC_TTLEXPIRED",
    144: "EGTS_PC_NO_ACK",
    145: "EGTS_PC_OBJ_NFOUND",
    146: "EGTS_PC_EVNT_NFOUND",
    147: "EGTS_PC_SRVC_NFOUND",
    148: "EGTS_PC_SRVC_DENIED",
    149: "EGTS_PC_SRVC_UNKN",
    150: "EGTS_PC_AUTH_DENIED",
    151: "EGTS_PC_ALREADY_EXISTS",
    152: "EGTS_PC_ID_NFOUND",
    153: "EGTS_PC_INC_DATETIME",
    154: "EGTS_PC_IO_ERROR",
    155: "EGTS_PC_NO_RES_AVAIL",
    156: "EGTS_PC_MODULE_FAULT",
    157: "EGTS_PC_MODULE_PWR_FLT",
    158: "EGTS_PC_MODULE_PROC_FLT",
    159: "EGTS_PC_MODULE_SW_FLT",
    160: "EGTS_PC_MODULE_FW_FLT",
    161: "EGTS_PC_MODULE_IO_FLT",
    162: "EGTS_PC_MODULE_MEM_FLT",
    163: "EGTS_PC_TEST_FAILED",
}
